	`define N(n)                            [(n)-1:0]
	`define IDX(x,n)                        ((x)*(n))+:(n)	
	`define FFdef(signal,val)               always @(posedge clk or negedge rst_n) if ( ~rst_n )  signal <= val; else 
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE2_115(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// Sma //////////
	input 		          		SMA_CLKIN,
	output		          		SMA_CLKOUT,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// EX_IO //////////
	inout 		     [6:0]		EX_IO,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// LCD //////////
	output		          		LCD_BLON,
	inout 		     [7:0]		LCD_DATA,
	output		          		LCD_EN,
	output		          		LCD_ON,
	output		          		LCD_RS,
	output		          		LCD_RW,

	//////////// RS232 //////////
	input 		          		UART_CTS,
	output		          		UART_RTS,
	input 		          		UART_RXD,
	output		          		UART_TXD,

	//////////// PS2 for Keyboard and Mouse //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// SDCARD //////////
	output		          		SD_CLK,
	inout 		          		SD_CMD,
	inout 		     [3:0]		SD_DAT,
	input 		          		SD_WP_N,

	//////////// VGA //////////
	output		     [7:0]		VGA_B,
	output		          		VGA_BLANK_N,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// I2C for EEPROM //////////
	output		          		EEP_I2C_SCLK,
	inout 		          		EEP_I2C_SDAT,

	//////////// I2C for Audio Tv-Decoder  //////////
	output		          		I2C_SCLK,
	inout 		          		I2C_SDAT,

	//////////// Ethernet 0 //////////
	output		          		ENET0_GTX_CLK,
	input 		          		ENET0_INT_N,
	input 		          		ENET0_LINK100,
	output		          		ENET0_MDC,
	inout 		          		ENET0_MDIO,
	output		          		ENET0_RST_N,
	input 		          		ENET0_RX_CLK,
	input 		          		ENET0_RX_COL,
	input 		          		ENET0_RX_CRS,
	input 		     [3:0]		ENET0_RX_DATA,
	input 		          		ENET0_RX_DV,
	input 		          		ENET0_RX_ER,
	input 		          		ENET0_TX_CLK,
	output		     [3:0]		ENET0_TX_DATA,
	output		          		ENET0_TX_EN,
	output		          		ENET0_TX_ER,
	input 		          		ENETCLK_25,

	//////////// Ethernet 1 //////////
	output		          		ENET1_GTX_CLK,
	input 		          		ENET1_INT_N,
	input 		          		ENET1_LINK100,
	output		          		ENET1_MDC,
	inout 		          		ENET1_MDIO,
	output		          		ENET1_RST_N,
	input 		          		ENET1_RX_CLK,
	input 		          		ENET1_RX_COL,
	input 		          		ENET1_RX_CRS,
	input 		     [3:0]		ENET1_RX_DATA,
	input 		          		ENET1_RX_DV,
	input 		          		ENET1_RX_ER,
	input 		          		ENET1_TX_CLK,
	output		     [3:0]		ENET1_TX_DATA,
	output		          		ENET1_TX_EN,
	output		          		ENET1_TX_ER,

	//////////// TV Decoder //////////
	input 		          		TD_CLK27,
	input 		     [7:0]		TD_DATA,
	input 		          		TD_HS,
	output		          		TD_RESET_N,
	input 		          		TD_VS,

	//////////// USB 2.0 OTG (Cypress CY7C67200) //////////
	output		     [1:0]		OTG_ADDR,
	output		          		OTG_CS_N,
	inout 		    [15:0]		OTG_DATA,
	input 		          		OTG_INT,
	output		          		OTG_RD_N,
	output		          		OTG_RST_N,
	output		          		OTG_WE_N,

	//////////// IR Receiver //////////
	input 		          		IRDA_RXD,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [31:0]		DRAM_DQ,
	output		     [3:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N,

	//////////// SRAM //////////
	output		    [19:0]		SRAM_ADDR,
	output		          		SRAM_CE_N,
	inout 		    [15:0]		SRAM_DQ,
	output		          		SRAM_LB_N,
	output		          		SRAM_OE_N,
	output		          		SRAM_UB_N,
	output		          		SRAM_WE_N,

	//////////// Flash //////////
	output		    [22:0]		FL_ADDR,
	output		          		FL_CE_N,
	inout 		     [7:0]		FL_DQ,
	output		          		FL_OE_N,
	output		          		FL_RST_N,
	input 		          		FL_RY,
	output		          		FL_WE_N,
	output		          		FL_WP_N,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);

	wire `N(32)  HEX_WORD;
    SEG7_LUT_8 u_seg (	HEX0,HEX1,HEX2,HEX3,HEX4,HEX5,HEX6,HEX7,HEX_WORD);	

//=======================================================
//  REG/WIRE declarations
//=======================================================

//=======================================================
//  Structural coding
//=======================================================

//-------------------------------------------------------------------------------
//System
//-------------------------------------------------------------------------------
	wire    clk;
	parameter  CLOCK_MHZ = 33;

	pll i_clock(
	    .inclk0                 (    CLOCK_50            ),
		.c0                     (    clk                 )
	);		
    wire    rst_n = KEY[0];
	
//-------------------------------------------------------------------------------
//uart
//-------------------------------------------------------------------------------    
	wire        tx_req;
	wire `N(8)  tx_byte;
	wire        rx_req;
	wire `N(8)  rx_byte;
	wire        rx_valid;
	wire        tx_ready;
	
	fpga_uart 
	#(
	    .BAUD               (   115200          ),
		.KHZ                (   CLOCK_MHZ*1000  )
	)                                           
	i_uart                                      
	(                                           
    .clk                    (    clk            ),
	.rst_n                  (    rst_n          ),
    .rx                     (    UART_RXD       ),
    .tx_req                 (    tx_req         ),
    .tx_byte                (    tx_byte        ),
    
    .rx_req                 (    rx_req         ),
    .rx_byte                (    rx_byte        ),
    .rx_valid               (    rx_valid       ),
    .tx                     (    UART_TXD       ),
    .tx_ready               (    tx_ready       )	
	);	

    parameter PICKING_NUM = 1;	
	wire                   rx_pk_valid;
	wire `N(PICKING_NUM+1) rx_pk_req_group;
	wire `N(8)             rx_pk_byte;
    uart_picking #(
	.PICKING_NUM            (    PICKING_NUM    )
	)i_uart_picking (	
    .clk                    (    clk            ),
	.rst_n                  (    rst_n          ),	
    .rx_req                 (    rx_req         ),
    .rx_byte                (    rx_byte        ),
    .rx_valid               (    rx_valid       ),
    .rx_pk_valid            (    rx_pk_valid    ),
	.rx_pk_req_group        (    rx_pk_req_group),
	.rx_pk_byte             (    rx_pk_byte     )
    );
	
	wire       uart_raw_req;
	wire `N(8) uart_raw_byte;
	uart_buffer i_uart_buffer (
    .clk                    (    clk            ),
    .rst_n                  (    rst_n          ),
	 
    .raw_vld                (    uart_raw_req   ),
    .raw_byte               (    uart_raw_byte  ),
	 
    .uart_tx_rdy            (    tx_ready       ),
    .uart_tx_vld            (    tx_req         ),
    .uart_tx_byte           (    tx_byte        )
);

	
//-------------------------------------------------------------------------------
//CPU
//-------------------------------------------------------------------------------   

    wire                   inner2imem_requ_vd;
	wire `N(`XLEN)         inner2imem_requ_addr;
	wire                   imem2inner_resp_vd;
	wire `N(`INUM*`XLEN)   imem2inner_resp_rdata;
	
    wire                   pipe2inner_queue_barrier;
	wire                   pipe2inner_break_vd;
	wire `N(`XLEN)         pipe2inner_break_pc;
	
	wire                   inner2dmem_requ_csr_active;
	wire                   inner2dmem_requ_vd;
	wire                   inner2dmem_requ_cmd;
	wire `N(2)             inner2dmem_requ_width;
	wire `N(`XLEN)         inner2dmem_requ_addr;
	wire `N(`XLEN)         inner2dmem_requ_wdata;
	wire                   dmem2inner_resp_vd;
	wire `N(`XLEN)         dmem2inner_resp_rdata;
	
    `define INNER_ENABLE
	
`ifdef INNER_ENABLE   
	rwa_top dut (
	    .rst_n                            (    rst_n                            ),
		.clk                              (    clk                              ),

		.pbuf2inner_active                (    0                                ),
		.pbuf2inner_vd                    (    0                                ),
		.pbuf2inner_instr                 (    0                                ),
		.inner2pbuf_rdy                   (                                     ),

		.inner2imem_requ_vd               (    inner2imem_requ_vd               ),
	    .inner2imem_requ_addr             (    inner2imem_requ_addr             ),
		.imem2inner_resp_req_ack          (    1                                ),
		.imem2inner_resp_vd               (    imem2inner_resp_vd               ),
		.imem2inner_resp_er               (    0                                ),
		.imem2inner_resp_rdata            (    imem2inner_resp_rdata            ),
 
		.pipe2inner_sstep                 (    0                                ),
		.pipe2inner_queue_barrier         (    pipe2inner_queue_barrier         ),
		.pipe2inner_break_vd              (    pipe2inner_break_vd              ),
		.pipe2inner_break_pc              (    pipe2inner_break_pc              ),
		.pipe2inner_hwbrkpt_instr         (    0                                ),
		.pipe2inner_hwbrkpt_data          (    0                                ),
	    .inner2pipe_queue_vd              (                                     ),
	    .inner2pipe_queue_rdy             (                                     ),
	    .inner2pipe_queue_pc_curr         (                                     ),
	    .inner2pipe_queue_pc_next         (                                     ),
	    .inner2pipe_queue_lsu_vd          (                                     ),
	    .inner2pipe_queue_lsu_load        (                                     ),
	    .inner2pipe_queue_lsu_save        (                                     ),
	    .inner2pipe_queue_lsu_addr        (                                     ),
	    .inner2pipe_queue_exc_req         (                                     ),
	    .inner2pipe_queue_exc_code        (                                     ),
	    .inner2pipe_queue_exc_trap_val    (                                     ),
	    .inner2pipe_queue_wfi_req         (                                     ),
	    .inner2pipe_queue_mret_req        (                                     ),		
	    .inner2pipe_pnd                   (                                     ),
		
        .inner2dmem_requ_csr_active       (    inner2dmem_requ_csr_active       ),
	    .inner2dmem_requ_vd               (    inner2dmem_requ_vd               ),
	    .inner2dmem_requ_cmd              (    inner2dmem_requ_cmd              ),
	    .inner2dmem_requ_width            (    inner2dmem_requ_width            ),
	    .inner2dmem_requ_addr             (    inner2dmem_requ_addr             ),
	    .inner2dmem_requ_wdata            (    inner2dmem_requ_wdata            ),
	    .dmem2inner_resp_req_ack          (    1                                ),
	    .dmem2inner_resp_vd               (    dmem2inner_resp_vd               ),
	    .dmem2inner_resp_er               (    0                                ),
	    .dmem2inner_resp_rdata            (    dmem2inner_resp_rdata            )		
	);
`endif

//-------------------------------------------------------------------------------
//CPU
//-------------------------------------------------------------------------------   

	wire                   prog_requ_vd;
	wire                   prog_requ_cmd;
	wire `N(2)             prog_requ_width;
	wire `N(16)            prog_requ_addr;
	wire `N(`XLEN)         prog_requ_wdata;
	
	wire  key_go    =  rx_pk_valid & rx_pk_req_group[0];
	wire  key_space =  (rx_pk_byte==" ");
	wire  key_one   =  (rx_pk_byte=="1");
    wire  key_two   =  (rx_pk_byte=="2");	
	wire  key_three =  (rx_pk_byte=="3");
	wire  key_other =  ~( key_space|key_one|key_two|key_three );

    //To switch between RUN/PROG
    reg   mode_run;
	reg   mode_verify;
	reg   mode_prog;
	
	wire run_in  = key_go & key_one;
	wire run_out = key_go & (key_two|key_three);
	`FFdef(mode_run,0)  mode_run <= run_in ? 1 : ( run_out ? 0 : mode_run );
	
	wire verify_in  = key_go & key_two;
	wire verify_out = key_go & (key_one|key_three);
    `FFdef(mode_verify,0) mode_verify <= verify_in ? 1 : ( verify_out ? 0 : mode_verify );
    
    wire prog_in  = key_go & key_three;
    wire prog_out = key_go & (key_one|key_two);
    `FFdef(mode_prog,1) mode_prog <= prog_in ? 1 : ( prog_out ? 0 : mode_prog );	
	
	//Write mem addr
	reg        prog_wr_full;
    reg `N(16) prog_wr_addr;	
	`FFdef(prog_wr_full,0) prog_wr_full <= mode_prog ? ( (prog_wr_addr==16'hffff) ? 1 : prog_wr_full ) : 0;
    `FFdef(prog_wr_addr,0) prog_wr_addr <= mode_prog ? ((~prog_wr_full & rx_req) ? (prog_wr_addr+1) : prog_wr_addr) : 0;

    //Read mem addr
	wire       prog_rd_start = mode_verify & key_go & key_space;
	
	reg        prog_rd_flag;
	reg `N(16) prog_rd_cnt;
	`FFdef(prog_rd_flag,0) prog_rd_flag <= prog_rd_start ? 1 : ( ( prog_rd_flag & (prog_rd_cnt==16'h200) ) ? 0 : prog_rd_flag );
	`FFdef(prog_rd_cnt,0)   prog_rd_cnt <= prog_rd_flag ? ( prog_rd_cnt+1 ) : 0;
	
	assign    prog_requ_vd = mode_prog ? (~prog_wr_full & rx_req) :    prog_rd_flag;
	assign   prog_requ_cmd = mode_prog ?                        1 :               0;
	assign prog_requ_width = 0;
	assign  prog_requ_addr = mode_prog ?             prog_wr_addr :     prog_rd_cnt;
	assign prog_requ_wdata = mode_prog ?                  rx_byte :               0;

    wire                   inner2dmem_requ_vd_4ram = inner2dmem_requ_vd & ~inner2dmem_requ_csr_active & (inner2dmem_requ_addr[31:16]==0);
	wire                   ram_requ_vd     = (~mode_run) ?  prog_requ_vd     : inner2dmem_requ_vd_4ram;
	wire                   ram_requ_cmd    = (~mode_run) ?  prog_requ_cmd    : inner2dmem_requ_cmd;
	wire `N(2)             ram_requ_width  = (~mode_run) ?  prog_requ_width  : inner2dmem_requ_width;
	wire `N(`XLEN)         ram_requ_addr   = (~mode_run) ?  prog_requ_addr   : inner2dmem_requ_addr;
	wire `N(`XLEN)         ram_requ_wdata  = (~mode_run) ?  prog_requ_wdata  : inner2dmem_requ_wdata;
	wire                   ram_resp_vd;
	wire `N(`XLEN)         ram_resp_rdata;	
	
	//reg `N(`XLEN) debug_word;
	//`FFdef(debug_word,32'h55aa55aa) debug_word <= ( mode_run & ram_requ_vd & ram_requ_cmd & (ram_requ_addr[15:4]==0)) ? {debug_word,inner2imem_requ_addr[15:0]} : debug_word;
	
	//assign HEX_WORD = debug_word;

	inner_memory i_memory(
	    .clk                     (    clk                    ),
		.rst_n                   (    rst_n                  ),
		
		.imem_requ_vd            (    inner2imem_requ_vd     ),
		.imem_requ_addr          (    inner2imem_requ_addr   ),
		
		.imem_resp_vd            (    imem2inner_resp_vd     ),
		.imem_resp_rdata         (    imem2inner_resp_rdata  ),
		
		.dmem_requ_vd            (    ram_requ_vd            ),
		.dmem_requ_cmd           (    ram_requ_cmd           ),
		.dmem_requ_width         (    ram_requ_width         ),
		.dmem_requ_addr          (    ram_requ_addr          ),
		.dmem_requ_wdata         (    ram_requ_wdata         ),

		.dmem_resp_vd            (    ram_resp_vd            ),
		.dmem_resp_rdata         (    ram_resp_rdata         )	
	);	

    led_status #(
    .LED_NUM                (    5                    ),
	.MHZ                    (    CLOCK_MHZ            ),
	.MULT_MS                (    800                  )
	) i_led_greenh (                                   
    .clk                    (    clk                  ),
    .rst_n                  (    rst_n                ),
	.enable                 (    mode_verify          ),
    .pulse                  (    prog_requ_vd         ),
    .led                    (    LEDG[8:5]            )	
	);

    led_status #(
    .LED_NUM                (    5                    ),
	.MHZ                    (    CLOCK_MHZ            ),
	.MULT_MS                (    800                  )
	) i_led_greenl (                                   
    .clk                    (    clk                  ),
    .rst_n                  (    rst_n                ),
	.enable                 (    mode_prog            ),
    .pulse                  (    prog_requ_vd         ),
    .led                    (    LEDG[4:0]            )	
	);
	
    led_status #(
    .LED_NUM                (    9                    ),
	.MHZ                    (    CLOCK_MHZ            ),
	.MULT_MS                (    1000                 )
	) i_led_redh (
    .clk                    (    clk                  ),
    .rst_n                  (    rst_n                ),
	.enable                 (    mode_run             ),
    .pulse                  (    inner2imem_requ_vd   ),
    .led                    (    LEDR[17:9]           )	
	);	

    led_status #(
    .LED_NUM                (    9                    ),
	.MHZ                    (    CLOCK_MHZ            ),
	.MULT_MS                (    1000                 )
	) i_led_redl (                                    
    .clk                    (    clk                  ),
    .rst_n                  (    rst_n                ),
	.enable                 (    mode_run             ),
    .pulse                  (    inner2dmem_requ_vd   ),
    .led                    (    LEDR[8:0]            )	
	);	
	
	assign      pipe2inner_queue_barrier = ~mode_run;

    reg  barrier_delay;
    `FFdef(barrier_delay,0) barrier_delay <= pipe2inner_queue_barrier;
    wire barrier_falling = 	barrier_delay & ~pipe2inner_queue_barrier;
	
	reg  restart_signal;
	`FFdef(restart_signal,0) restart_signal <= mode_run & key_go & key_space;
	
	assign           pipe2inner_break_vd = barrier_falling|restart_signal;
	assign           pipe2inner_break_pc = 32'h200;

    assign uart_raw_req  =  key_go      ? (key_one|key_two|key_three) :
                            mode_verify ? ram_resp_vd    : 
                                          (mode_run & inner2dmem_requ_vd & ~inner2dmem_requ_csr_active & inner2dmem_requ_cmd & ( inner2dmem_requ_addr==32'hf000_0000 ) );
    assign uart_raw_byte = 	key_go      ? rx_pk_byte     :
                            mode_verify ? ram_resp_rdata : 
                                          inner2dmem_requ_wdata[7:0];
	
	reg   `N(7)        mtime_cnt;
	reg   `N(`XLEN)    mtime_val;
	reg   `N(2*`XLEN)  mcycle_val;	
	`FFdef(mtime_cnt,0)  mtime_cnt  <= ( mtime_cnt==99 ) ? 0 : ( mtime_cnt + 1'b1 );
	`FFdef(mtime_val,0)  mtime_val  <= ( mtime_cnt==99 ) ? ( mtime_val + 1'b1 ) : mtime_val;
	`FFdef(mcycle_val,0) mcycle_val <= mcycle_val + 1;
	
	reg        csr_sel;
	reg `N(12) csr_addr;
	`FFdef(csr_sel,0)    csr_sel <= inner2dmem_requ_vd ? inner2dmem_requ_csr_active : csr_sel;
	`FFdef(csr_addr,0)  csr_addr <= inner2dmem_requ_vd ? inner2dmem_requ_addr       : csr_addr;
	
	reg   `N(`XLEN)     dmem2inner_rdata;
	always @* begin
	    dmem2inner_rdata = ram_resp_rdata;
		if ( csr_sel ) begin
		    case(csr_addr)
			12'hc01 : dmem2inner_rdata = mtime_val;
			12'hc00 : dmem2inner_rdata = mcycle_val;
			12'hc80 : dmem2inner_rdata = mcycle_val>>`XLEN;
			endcase
	    end
	end
	
	assign dmem2inner_resp_vd    = 1;
	assign dmem2inner_resp_rdata = dmem2inner_rdata;
	
	reg `N(`XLEN)   csr_data;
	`FFdef(csr_data,0) csr_data <= csr_sel ? dmem2inner_rdata : csr_data;
	
	assign HEX_WORD = csr_data;

endmodule

module SEG7_LUT	(	oSEG,iDIG	);
input	[3:0]	iDIG;
output	[6:0]	oSEG;
reg		[6:0]	oSEG;

always @(iDIG)
begin
		case(iDIG)
		4'h1: oSEG = 7'b1111001;	// ---t----
		4'h2: oSEG = 7'b0100100; 	// |	  |
		4'h3: oSEG = 7'b0110000; 	// lt	 rt
		4'h4: oSEG = 7'b0011001; 	// |	  |
		4'h5: oSEG = 7'b0010010; 	// ---m----
		4'h6: oSEG = 7'b0000010; 	// |	  |
		4'h7: oSEG = 7'b1111000; 	// lb	 rb
		4'h8: oSEG = 7'b0000000; 	// |	  |
		4'h9: oSEG = 7'b0011000; 	// ---b----
		4'ha: oSEG = 7'b0001000;
		4'hb: oSEG = 7'b0000011;
		4'hc: oSEG = 7'b1000110;
		4'hd: oSEG = 7'b0100001;
		4'he: oSEG = 7'b0000110;
		4'hf: oSEG = 7'b0001110;
		4'h0: oSEG = 7'b1000000;
		endcase
end

endmodule

module SEG7_LUT_8 (	oSEG0,oSEG1,oSEG2,oSEG3,oSEG4,oSEG5,oSEG6,oSEG7,iDIG );
input	[31:0]	iDIG;
output	[6:0]	oSEG0,oSEG1,oSEG2,oSEG3,oSEG4,oSEG5,oSEG6,oSEG7;

SEG7_LUT	u0	(	oSEG0,iDIG[3:0]		);
SEG7_LUT	u1	(	oSEG1,iDIG[7:4]		);
SEG7_LUT	u2	(	oSEG2,iDIG[11:8]	);
SEG7_LUT	u3	(	oSEG3,iDIG[15:12]	);
SEG7_LUT	u4	(	oSEG4,iDIG[19:16]	);
SEG7_LUT	u5	(	oSEG5,iDIG[23:20]	);
SEG7_LUT	u6	(	oSEG6,iDIG[27:24]	);
SEG7_LUT	u7	(	oSEG7,iDIG[31:28]	);

endmodule
